### ISSUE TITLE
Submit patch

### ISSUE THREAD

**Issue by IurmanJ** [IurmanJ/kernel_ipv6_ioam#9]
Merge patch upstream. For that, we need to replace ioctl with netlink (or even rtnetlink), and also use lightweight tunnels (lwtunnel). Actually, we can go the same way as segment routing, which means that the insertion/encapsulation process would be configured by iproute2. But still, we would need *something* to configure a node (another control plane agent equivalent to iproute2), e.g for IOAM namespaces and per-namespace data (per-node data in general), which is mandatory for the IOAM data plane to work.

Build it upon the new patch that brings better infrastructure for EHs: https://lwn.net/Articles/801298/

**Comment by brotherdust** [comment]
Hi @IurmanJ!
This is some great work! Any idea when you'll be submitting it upstream? I'm sure the `net-next` folks would love to see it!

**Comment by IurmanJ** [comment]
Hey @brotherdust,

Thanks! I actually did send a patch already, see [this link](https://lore.kernel.org/netdev/20200624192310.16923-1-justin.iurman@uliege.be/). I'm working on the v2, with some improvements over the v1, which will also include the insertion/encapsulation, just like the patch on this repo (improved, of course).

**Comment by brotherdust** [comment]
So cool! Keep up the great work! I don't have anything to offer as far as coding skills, but if you need some documentation done, I can contribute a few hours here and there!

**Comment by IurmanJ** [comment]
See [https://lore.kernel.org/netdev/20210401182338.24077-1-justin.iurman@uliege.be](https://lore.kernel.org/netdev/20210401182338.24077-1-justin.iurman@uliege.be). Closing this "issue" since the patchset has been submitted (version 3 already) and is waiting for (hopefully) its final review. Note that the corresponding iproute2 patchset is also ready and available on this repo.

**Comment by IurmanJ** [comment]
@brotherdust Just to keep you up to date, the IOAM patch-set has been merged into net-next approx a month ago and will be part of the kernel in the 5.14 release (available in a few weeks). The iproute2 tool will also include support for IOAM in next release (iproute2 5.14).

I'm currently working on two other important IOAM things to include but it'll probably be for 5.15 (as the merge window for 5.14 is near).

I'll try to update the master branch of this repo ASAP to only include documentation and configuration examples. Ping me if you have any questions.

**Comment by brotherdust** [comment]
Oh wow! That's so cool! I'll make sure to try it out ASAP!
